language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"
# command to run tests
script:
  - test/test_B2YBank.py
notifications:
	webhooks:
		urls:
		  - https://webhooks.gitter.im/e/23be690947c65bd7a84b
		on_success: change  # options: [always|never|change] default: always
		on_failure: always  # options: [always|never|change] default: always
		on_start: never     # options: [always|never|change] default: always