language: python
python:
  - "nightly"
  - "3.7-dev" # 3.7 development branch
  - "3.6-dev" # 3.6 development branch
  - "3.6"
  - "3.5-dev" # 3.5 development branch
  - "3.5"
  - "3.4"
  - "2.7"
# install what's needed to run tests
install:
  - pip install flake8
  - pip install coverage; fi
  - pip install codecov; fi
# command to run tests
script:
  - python -m unittest discover -v
  - python bank2ynab.py
  - flake8 --builtins=unicode; fi
  - coverage run bank2ynab.py; fi
after_success:
  - codecov; fi
  - coverage report; fi
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/23be690947c65bd7a84b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
